# DO NOT CHANGE the "init" and "install" sections below

# Download script file from GitHub
init:
  ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'
install:
  ps: Bootstrap

environment:
  global:
    WARNINGS_ARE_ERRORS:
    RTOOLS_VERSION: 34 
    USE_RTOOLS: true

  matrix:
  - R_VERSION: release
    R_ARCH: x64

build_script:
  - travis-tool.sh install_deps
  - R CMD build --no-build-vignettes --no-manual --no-resave-data .
  - R CMD INSTALL pbdZMQ*.tar.gz
  - Rscript --arch i386 -e "pbdZMQ::get.zmq.cppflags(arch='/i386')"
  - Rscript --arch x64 -e "pbdZMQ::get.zmq.cppflags(arch='/x64')"
  - Rscript --arch i386 -e "pbdZMQ::test.load.zmq(arch='/i386')"
  - Rscript --arch i386 -e "pbdZMQ::test.load.zmq(arch='/x64')"
